apiVersion: v1
kind: Service
metadata:
  labels:
    app: whereami-grpc
  name: whereami-grpc
  namespace: grpc-h2c
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    name: grpc # adding for Istio
    appProtocol: kubernetes.io/h2c # using HTT2 cleartext over TCP
  selector:
    app: whereami-grpc
  type: ClusterIP