apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: my-grpc-multicluster-health-check
  namespace: grpc-h2c
spec:
  targetRef:
    group: net.gke.io # if this is single-cluster, use "" instead
    kind: ServiceImport # targeting a service import instead of a service, because i'm using multicluster. if this is single-cluster, use kind: Service 
    name: whereami-grpc
  default:
    config:
      type: GRPC # see here: https://cloud.google.com/load-balancing/docs/health-check-concepts#criteria-protocol-grpc - TLS support is in preview
      grpcHealthCheck:
        port: 9090 # The port your gRPC service is running on.
        #grpcServiceName: "" # The name of the gRPC service to check. "" for the overall server.
    timeoutSec: 10
    checkIntervalSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 3